name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify VITE_API_URL secret
        run: |
          if [ -n "${{ secrets.VITE_API_URL }}" ]; then
            echo "✅ VITE_API_URL is set: ${{ secrets.VITE_API_URL }}"
          else
            echo "⚠️ CRITICAL ERROR: VITE_API_URL is empty!"
            exit 1
          fi
      
      - name: Build web application with API URL
        run: VITE_API_URL=${{ secrets.VITE_API_URL }} npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
      
      - name: Create Android project
        run: npx cap add android
      
      - name: Sync Capacitor
        run: npx cap sync android
      
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
      
      - name: Build Android Debug APK
        run: cd android && ./gradlew assembleDebug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
      
      - name: Show APK info
        run: |
          APK_PATH="android/app/build/outputs/apk/debug/app-debug.apk"
          APK_SIZE=$(du -h "$APK_PATH" | cut -f1)
          echo "✅ APK built successfully!"
          echo "📦 Size: $APK_SIZE"
          echo "📍 Location: $APK_PATH"
